function largestElement(arr) {
    if (!arr) {
        return "No input received";
    } else if (!arr.length) {
        return "Hey!, I need multiple values, I am an array!";
    } else {
        let num = [0, 0, 0];
        for (let j = 0; j < arr.length; j++) {
            if (arr[j] > num[0]) {
                num[2] = num[1];
                num[1] = num[0];
                num[0] = arr[j];
            } else if (arr[j] > num[1]) {
                num[1] = num[0];
                num[0] = arr[j];
            } else if (arr[j] > num[2]) {
                num[2] = arr[j];
            }
        }
        return num;
    }
}

let numArray = [];
let num = 0;
for (let i = 0; i < 20; i++) {
    do {
        num = Math.floor(Math.random() * 100) + 1;
    } while (numArray.includes(num));
    {
        numArray.push(num);
    }
}
let output = largestElement(numArray);
console.log(`Autogenerated array: - [${numArray}]`);
console.log(`Largest three elements: - ${output}`);
